# Generated by Django 5.0 on 2023-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_address', models.CharField(max_length=255)),
                ('shop_coordinatez_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shop_coordinatez_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'Coffee Shop',
                'verbose_name_plural': 'Coffee Shops',
                'db_table': 'coffee_shop',
            },
        ),
    ]
