# Generated by Django 5.0 on 2023-12-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_alter_coffeeshop_shop_coordinatez_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeshop',
            old_name='shop_coordinatez_latitude',
            new_name='shop_coordinate_latitude',
        ),
        migrations.RenameField(
            model_name='coffeeshop',
            old_name='shop_coordinatez_longitude',
            new_name='shop_coordinate_longitude',
        ),
    ]
